apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test-temp
  name: test-temp
spec:
  containers:
  - image: nginx
    name: test-temp
    volumeMounts:
    - mountPath: /temp
      name: emptydir
  volumes:
  - name: emptydir
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: test-temp-service
spec:
  type: NodePort
  selector:
    app: test-temp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
