apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: jenkins
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
    nodePort: 30303
  - port: 50000
    protocol: TCP
    name: secondary
    nodePort: 30001
  selector:
    app: jenkins
