apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hostpath-test
  name: hostpath-test
spec:
  containers:
  - image: nginx
    name: test
    volumeMounts:
    - mountPath: /temnp
      name: hostpath
  volumes:
  - name: hostpath
    hostPath:
      path: /etc/opt
---
apiVersion: v1
kind: Service
metadata:
  name: hostpath-service
spec:
  type: NodePort
  selector:
    app: hostpath-test
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30040