apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
spec:
  containers:
    - name: nfs-test
      image: nginx
      volumeMounts:
      - mountPath: "/temp"
        name: pv-nfs
  volumes:
    - name: pv-nfs
      persistentVolumeClaim:
        claimName: pvc-nfs