apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: pv-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi