apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    app: pv1
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
   path: /0325/db/pv