apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pv1
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: pv1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi