apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pv2
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: pv2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi