apiVersion: v1
kind: Service
metadata:
  name: pod1-nodeport
spec:
  type: NodePort
  selector:
    app: pod1
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 3000
     nodePort: 30001
