apiVersion: v1
kind: Pod
metadata:
  name: webpod
  labels:
    app: webpod
spec:
  containers:
    - name: webpod
      image: wotkddl21/k8s:web
      ports:
      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: webpod
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
